const sampleItem = [
    {
      type:"mobiles",
      title: "Oppo K13",
      description:"Oppo K12 5G (light Green)",
      specification:"8GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH| 64MP +2Mp +2MP| 32MP front Camera",
      image:"https://fdn2.gsmarena.com/vv/bigpic/oppo-k12.jpg",
      price: 18000,
    },
    {
      type:"earbuds",
      title:"Mivi DuoPods D3",
      description:"Mivi DuoPods D3 TWS,13mm Driver,Rich Bass,50H Playtime",
      specification:"With Mic:Yes|Connector Type: No|Bluetooth version: 5.3 | Wireless range: 10 m|Type-C Charging | 10 mins charge = 500 mins playtime",
      image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/w/p/m/-original-imagrvmgmhdk6msy.jpeg?q=70",
      price:599
    },
    {
      type:"mobiles",
      title: "Oppo F20 Pro",
      description:"Oppo F20 5G (light Brown)",
      specification:"8GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH| 128MP +2Mp +2MP| 32MP front Camera",
      image:"https://fdn2.gsmarena.com/vv/bigpic/oppo-f25-pro.jpg",
      price: 23999,
      
    },
    {
        type:"laptops",
        title: "Dell Intel Core i3",
        description:"DELL Intel Core i3 12th Gen 1215U -",
        specification:" (8 GB/512 GB SSD/Windows 11 Home) New Inspiron 15 Laptop Thin and Light Laptop  (38 cm, Carbon Black, 1.65 Kg, With MS Office)",
        image:"https://rukminim2.flixcart.com/image/312/312/l1fc0i80/computer/9/5/r/inspiron-3525-thin-and-light-laptop-dell-original-imagczzfezyd7tqs.jpeg?q=70",
        price:34990,
    },
    {
      type:"watches",
      title: "Oppo watch SE",
      description:"OPPO Watch Free Smartwatch  (Black Strap, Free Size)",
      specification:"Lightweight 1.64 AMOLED Display:makes it possible to display more content.33g Ultralight Design:The user will hardly feel anything wearing it while sleeping",
      image:"https://fdn2.gsmarena.com/vv/pics/oppo/oppo-watch-se-01.jpg",
      price: 2500,
    },
    {
        type:"mobiles",
        title: "Oppo K11",
        description:"Oppo K11 5G (Black)",
        specification:"8GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH| 64MP +2Mp +2MP| 32MP front Camera",
        image:"https://fdn2.gsmarena.com/vv/pics/oppo/oppo-k11-2.jpg",
        price: 18500,
    },
    {
        type:"earbuds",
        title:"boAt Airdopes Alpha",
        description:"boAt Airdopes Alpha with 35 HRS Playback, 13mm Drivers, Dual Mics",
        specification:"With mic:yes|35 hours of playback|boat signature sound 13mm drivers ASAP charge(10min=120min",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/f/i/7/-original-imagqre9pyfawzcg.jpeg?q=70",
        price:799
    },
    {
        type:"mobiles",
        title: "Oppo Reno 10",
        description:"Oppo Reno 10 5G (Sky blue)",
        specification:"8GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH| 64MP +2Mp +2MP| 32MP front Camera",
        image:"https://fdn2.gsmarena.com/vv/pics/oppo/oppo-reno10-international-1.jpg",
        price: 26000,
    },
    {
        type:"cables",
        title:"Bestor USB Type C Cable 2A",
        description:"Bestor USB Type C Cable 2 A 1.2 m Multi Charging Cable",
        specification:"Length 1.2m|Round cable|cable Speed:480Mb/s| (Compatible with SMART PHONE, IOS, ANDROID, Red, One Cable)",
        image:"https://rukminim2.flixcart.com/image/612/612/l02r1jk0/data-cable/usb-type-c-cable/4/x/f/multi-charging-cable-4ft-3-in-1-nylon-braided-multiple-usb-fast-original-imagby3hkzgvvpny.jpeg?q=70",
        price:349
    },
    {
        type:"mobiles",
        title: "Oppo F23",
        description:"Oppo F23 5G (Bold Gold)",
        specification:"8GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH | 64MP +2Mp +2MP| 32MP front Camera",
        image:"https://fdn2.gsmarena.com/vv/pics/oppo/oppo-f23-5g-1.jpg",
        price: 21000,
    },
    {
        type:"mobiles",
        title: "OnePlus Nord N30",
        description:"Oppo Nord N30 5G (BLack)",
        specification:"6GB RAM|128 GB ROM|Expandable Upto 1TB|Battery 4500MAH | 64MP +2Mp +2MP| 16MP front Camera",
        image:"https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-n30-se-5g-4.jpg",
        price: 17000,
    },
    {
        type:"pc",
        title:"ASUS Vivo AiO V222",
        description:"ASUS Vivo AiO V222, All in One Desktop, Intel Pentium Quad Core (8 GB DDR4/256 GB SSD/Windows 11 Home",
        specification:"Window 11 Home| Intel pentium Quad Core|Ram 8GB DDR4| 21.5 inch Display",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/allinone-desktop/a/y/a/-original-imagtvpxrzjrapg4.jpeg?q=70",
        price:30990
    },
    {
        type:"mobiles",
        title: "OnePlus 12R",
        description:"One Plus 12R 5G (Sky blue)",
        specification:"6GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH | 64MP +2Mp +2MP| 32MP front Camera",
        image:"https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12r-1.jpg",
        price: 22000,
    },
    {
        type:"pc",
        title:"ZEBRONICS Intel Core i5",
        description:"ZEBRONICS Intel Core i5 (16 GB / 1 TB / Windows 10)",
        specification:"ZEBRONICS Intel Core i5 (16 GB / 1 TB / Windows 10) Assembled Desktop Computer  (19 inch Display)",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/desktop-computer/a/s/0/1-i5-2tb-zebronics-original-imagzqbzybqqgvhw.jpeg?q=70",
        price:14490
    },
    {
        type:"mobiles",
        title: "OnePlus Open",
        description:"One Plus Open 5G (light Green)",
        specification:"8GB RAM|256 GB ROM|Expandable Upto 1TB|Battery 5000MAH | 128MP +2Mp +2MP| 64MP front Camera",
        image:"https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-open-2.jpg",
        price: 29000,
    },
    {
        type:"monitors",
        title: "SAMSUNG 24 inch Full HD LED",
        description:"SAMSUNG 24 inch Full HD LED Backlit IPS Panel with 3-Sided Borderless Display, Game & Free Sync Mode, Eye Saver Mode & Flicker Free Monitor (LS24C310EAWXXL) ",
        specification:"panel Type:IPS panel|Screen Resolution Type:Full HD|Brightness:250nits| Response Time:5ms| Refresh Rate:75 Hz",
        image:"https://rukminim2.flixcart.com/image/312/312/xif0q/monitor/k/l/b/-original-imagsgh8zzgbu2tf.jpeg?q=70",
        price: 7399,
    },
    {
        type:"laptops",
        title: "Lenovo IdeaPad",
        description:"Lenevo IdeaPad Slim3 Intel Pentium Quad Core",
        specification:" (4 GB/256 GB SSD/Windows 10 Home) New Inspiron 15 Laptop Thin and Light Laptop  (38 cm, Carbon Black, 1.65 Kg, With MS Office)",
        image:"https://rukminim2.flixcart.com/image/312/312/xif0q/computer/b/i/x/-original-imahyfx77g4cxt75.jpeg?q=70",
        price:29990,
    },
    {
        type:"laptops",
        title: "HP AMD Ryzen 3",
        description:"HP AMD Ryzen 3 4500Series U- ",
        specification:" (8 GB/512 GB SSD/Windows 11 Home) New Inspiron 15 Laptop Thin and Light Laptop  (38 cm, Carbon Black, 1.65 Kg, With MS Office)",
        image:"https://rukminim2.flixcart.com/image/312/312/xif0q/computer/r/a/x/-original-imagykgpfafenrvw.jpeg?q=70",
        price:31990,
    },
    {
        type:"laptops",
        title: "ASUS VivoBook 15",
        description:"Asus VivoBook Core i3 12th Gen 1215U -",
        specification:" (4 GB/512 GB SSD/Windows 11 Home) New Inspiron 15 Laptop Thin and Light Laptop  (38 cm, Carbon Black, 1.65 Kg, With MS Office)",
        image:"https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/e/z/-original-imagpxgqesgrthks.jpeg?q=70",
        price:21990,
    },
    {
        type:"laptops",
        title: "DELL Intel Core i3",
        description:"DELL Intel Core i3 11th Gen 1215U -",
        specification:" (8 GB/512 GB SSD/Windows 11 Home) New Inspiron 15 Laptop Thin and Light Laptop  (38 cm, Carbon Black, 1.65 Kg, With MS Office)",
        image:"https://rukminim2.flixcart.com/image/312/312/l1fc0i80/computer/9/5/r/inspiron-3525-thin-and-light-laptop-dell-original-imagczzfezyd7tqs.jpeg?q=70",
        price:34990,
    },
    {
        type:"cpu",
        title: "DZAB Assembled",
        description:"DZAM Assembled Wireless rechargeable portable Premium bass Multimedia",
        specification:"Power Output(RMS): 9W Power Source Dc/Battery/Usb Battery life 4 hr | Charging time: 1.5 hr Bluetooth Version 4.2 Wireless range 10m  ",
        image:"https://rukminim2.flixcart.com/image/612/612/kk1h5e80/cpu/q/y/b/i3-dasktop-500gb-4gb-dgcam-original-imafzh26anfg9rrw.jpeg?q=70",
        price:6914,
    },
    {
        type:"cpu",
        title: "iball GAMING01 i5",
        description:"iball WORKSTATION03 i5-2400",
        specification:"Processor Type: Intel 3.1 GH|0.512 GB Intel® HD Graphics 2000 Graphics|Quad Core Mid Tower| GB DDR3 RAM| SSD capacity 128GB",
        image:"https://rukminim2.flixcart.com/image/612/612/l1v1uvk0/cpu/y/n/g/3-2-gaming-learning-500-s-s-enterprises-original-imagdbyfzg9q54vz.jpeg?q=70",
        price:9290,
    },
    {
        type:"cpu",
        title: "F FERONS Wireless",
        description:"F FERONS Wireless  rechargeable portable Premium bass Multimedia",
        specification:"Power Output(RMS): 3W Power Source Dc/Battery/Usb Battery life 2 hr | Charging time: 3 hr Bluetooth Version 3.1 Wireless range 5m  ",
        image:"https://rukminim2.flixcart.com/image/612/612/kqpj4i80/speaker/mobile-tablet-speaker/i/2/r/tg113-dimenight-original-imag4nzrbugmarpb.jpeg?q=70",
        price:387,
    },
    {
        type:"speakers",
        title: "boAt Stone 350 10W",
        description:"boAt Stone 350 10W  rechargeable portable Premium bass Multimedia",
        specification:"Power Output(RMS): 8W Power Source Dc/Battery/Usb Battery life 3 hr | Charging time: 3 hr Bluetooth Version 4.0 Wireless range 10m  ",
        image:"https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/r/b/4/stone-350-boat-original-imafyebgtg74sghe.jpeg?q=70",
        price:1299,
    },
    {
        type:"rams",
        title: "Crucial DDR3 DDR3 8 GB",
        description:"Crucial DDR3 DDR3 8 GB (Dual Channel) Laptop RAM (CT102464BF160B)  (Green)",
        specification:"Data rate:DDR3| Memory Configuration:8GB DDR3L 1600MHZ| Number of channel:Dual Channel|Compatiable Device:Laptop",
        image:"https://rukminim2.flixcart.com/image/612/612/kxuqdu80/ram/g/z/j/ct102464bf160b-crucial-original-imaga7pekkuscd6z.jpeg?q=70",
        price:  1195 ,
    },
    {
        type:"neckbands",
        title: "OnePlus Bullets Wireless",
        description:"OnePlus Bullets Wireless Z2 Bluetooth Headset  (Jazz Green, In the Ear)",
        specification:"with mic:yes|Bluetooth version:5| Battery life:20Hrs",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/a/8/bullets-wireless-z2-oneplus-original-imagpgskyzj6zhte.jpeg?q=70",
        price: 1399,
    },
    {
        type:"keyboards",
        title:"Aula F2023 Combo Wired USB",
        description:"Aula F2023 Combo Wired USB Gaming Keyboard  (Black)",
        specification:"Size:Standard | Interface:wired USB| RGB keyboard",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/computer-acc-combo/y/n/m/f2023-combo-premium-rgb-backlit-gaming-keyboard-mouse-with-6-original-imagr6v59ybqhyvx.jpeg?q=70",
        price:749
    },
    {
        type:"mouse",
        title:"Portronics Toad 13, POR 1381",
        description:"Portronics Toad 13, POR 1381 / Runs on single AA Battery,",
        specification:"30 Lakh+ click Life| Upto 12000 DPI wireless| Optical Mouse(2.4 GHz wireless black)|Compatibility: Windows 11, macOS 12 & higher versions",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/mouse/a/t/d/-original-imagwde4z4v2cy6g.jpeg?q=70",
        price:279
    }
    
   
  ];
  
  module.exports = { data: sampleItem };